### ISSUE TITLE
Clean up workflow

### ISSUE THREAD

**Issue by jjoeldaniel** [acmcsufoss/acmOpportunities#10]
We should be caching dependencies (example [here](https://github.com/jjoeldaniel/trends/blob/40bd17af76fb5a061fedf91ce8587b754586e82c/.github/workflows/main.yml#L20-L38)) as well as update to actions/checkout@v3

**Comment by boushrabettir** [comment]
Resolved [here](https://github.com/acmcsufoss/acmOpportunities/commit/b8ae202152283a4792a4558fc3a5adc32af191d0)

**Comment by jaasonw** [comment]
nothing about this resolves that issue

**Comment by jjoeldaniel** [comment]
Still missing update to [checkout@v3](https://github.com/actions/checkout)

**Comment by boushrabettir** [comment]
Resolved [here](https://github.com/acmcsufoss/acmOpportunities/pull/11/commits/d8306f9a7f573c0f56fa1490a3e25ca825f3fab0)
